---
site_name: Memento
site_description: My personal digital garden
site_author: m0wer
site_url: https://m0wer.github.io/memento
nav:
  - Introduction: index.md
    #  - Projects:
    #  - Organization:
  - Computer Science:
    - GNU/Linux:
      - Android: computer_science/gnu_linux/android.md
      - Android-studio: computer_science/gnu_linux/android-studio.md
      - Anki: computer_science/gnu_linux/anki.md
      - Ansible: computer_science/gnu_linux/ansible.md
      - APT: computer_science/gnu_linux/apt.md
      - Bash: computer_science/gnu_linux/bash.md
      - blkid: computer_science/gnu_linux/blkid.md
      - C: computer_science/gnu_linux/c.md
      - cpupower: computer_science/gnu_linux/cpupower.md
      - Debian: computer_science/gnu_linux/debian.md
      - dig: computer_science/gnu_linux/dig.md
      - Docker: computer_science/gnu_linux/docker.md
      - Eclipse: computer_science/gnu_linux/eclipse.md
      - elogind: computer_science/gnu_linux/elogind.md
      - emerge: computer_science/gnu_linux/emerge.md
      - equery: computer_science/gnu_linux/equery.md
      - ESP8266: computer_science/gnu_linux/esp8266.md
      - ExifTool: computer_science/gnu_linux/exiftool.md
      - fdisk: computer_science/gnu_linux/fdisk.md
      - FFmpeg: computer_science/gnu_linux/ffmpeg.md
      - find: computer_science/gnu_linux/find.md
      - Firefox: computer_science/gnu_linux/firefox.md
      - FTP: computer_science/gnu_linux/ftp.md
      - genkernel: computer_science/gnu_linux/genkernel.md
      - genlop: computer_science/gnu_linux/genlop.md
      - Gentoo: computer_science/gnu_linux/gentoo.md
      - Git: computer_science/gnu_linux/git.md
      - GPG: computer_science/gnu_linux/gpg.md
      - Ghostscript: computer_science/gnu_linux/ghostscript.md
      - Hushboard: computer_science/gnu_linux/hushboard.md
      - i3 window manager: computer_science/gnu_linux/i3wm.md
      - ibus: computer_science/gnu_linux/ibus.md
      - ImageMagick: computer_science/gnu_linux/imagemagick.md
      - iostat: computer_science/gnu_linux/iostat.md
      - iptables: computer_science/gnu_linux/iptables.md
      - isync: computer_science/gnu_linux/isync.md
      - Jabber: computer_science/gnu_linux/jabber.md
      - Java: computer_science/gnu_linux/java.md
      - jpegoptim: computer_science/gnu_linux/jpegoptim.md
      - Kali: computer_science/gnu_linux/kali.md
      - Kernel: computer_science/gnu_linux/kernel.md
      - Khal: computer_science/gnu_linux/khal.md
      - Khard: computer_science/gnu_linux/khard.md
      - Kodi: computer_science/gnu_linux/kodi.md
      - Latex: computer_science/gnu_linux/latex.md
      - Layman: computer_science/gnu_linux/layman.md
      - LibreOffice: computer_science/gnu_linux/libreoffice.md
      - LightDM: computer_science/gnu_linux/lightdm.md
      - Linux: computer_science/gnu_linux/linux.md
      - LUKS: computer_science/gnu_linux/luks.md
      - LVM: computer_science/gnu_linux/lvm.md
      - MarkDown: computer_science/gnu_linux/markdown.md
      - MathJax: computer_science/gnu_linux/mathjax.md
      - mdadm: computer_science/gnu_linux/mdadm.md
      - mimeopen: computer_science/gnu_linux/mimeopen.md
      - Molecule: computer_science/gnu_linux/molecule.md
      - Msmtp: computer_science/gnu_linux/msmtp.md
      - Music: computer_science/gnu_linux/music.md
      - NeoMutt: computer_science/gnu_linux/neomutt.md
      - netcat: computer_science/gnu_linux/netcat.md
      - Nextcloud: computer_science/gnu_linux/nextcloud.md
      - NFS: computer_science/gnu_linux/nfs.md
      - NGINX: computer_science/gnu_linux/nginx.md
      - nice: computer_science/gnu_linux/nice.md
      - Nikola: computer_science/gnu_linux/nikola.md
      - Octave: computer_science/gnu_linux/octave.md
      - OpenLDAP: computer_science/gnu_linux/openldap.md
      - OpenRC: computer_science/gnu_linux/openrc.md
      - OpenSSL: computer_science/gnu_linux/openssl.md
      - Pandoc: computer_science/gnu_linux/pandoc.md
      - Pass: computer_science/gnu_linux/pass.md
      - pdfimages: computer_science/gnu_linux/pdfimages.md
      - PDFtk: computer_science/gnu_linux/pdftk.md
      - pdfunite: computer_science/gnu_linux/pdfunite.md
      - Portage: computer_science/gnu_linux/portage.md
      - PostgreSQL: computer_science/gnu_linux/postgresql.md
      - PulseAudio: computer_science/gnu_linux/pulseaudio.md
      - qutebrowser: computer_science/gnu_linux/qutebrowser.md
      - Radare2: computer_science/gnu_linux/radare2.md
      - Ranger: computer_science/gnu_linux/ranger.md
      - Raspberry Pi: computer_science/gnu_linux/rpi.md
      - rsnapshot: computer_science/gnu_linux/rsnapshot.md
      - rsync: computer_science/gnu_linux/rsync.md
      - rxvt-unicode: computer_science/gnu_linux/rxvt-unicode.md
      - sed: computer_science/gnu_linux/sed.md
      - Shell: computer_science/gnu_linux/shell.md
      - Shell-utils: computer_science/gnu_linux/shell-utils.md
      - shnsplit: computer_science/gnu_linux/shnsplit.md
      - smartmontools: computer_science/gnu_linux/smartmontools.md
      - SSH: computer_science/gnu_linux/ssh.md
      - ss: computer_science/gnu_linux/ss.md
      - stat: computer_science/gnu_linux/stat.md
      - sysctl: computer_science/gnu_linux/sysctl.md
      - SystemD: computer_science/gnu_linux/systemd.md
      - Taskwarrior: computer_science/gnu_linux/taskwarrior.md
      - tcpdump: computer_science/gnu_linux/tcpdump.md
      - Telegraf: computer_science/gnu_linux/telegraf.md
      - telegram-cli: computer_science/gnu_linux/telegram-cli.md
      - Terminal: computer_science/gnu_linux/terminal.md
      - Termite: computer_science/gnu_linux/termite.md
      - tmux: computer_science/gnu_linux/tmux.md
      - TOR: computer_science/gnu_linux/tor.md
      - Vagrant: computer_science/gnu_linux/vagrant.md
      - vimdiff: computer_science/gnu_linux/vimdiff.md
      - vim: computer_science/gnu_linux/vim.md
      - virtualenvwrapper: computer_science/gnu_linux/virtualenvwrapper.md
      - WeeChat: computer_science/gnu_linux/weechat.md
      - wget: computer_science/gnu_linux/wget.md
      - xcip: computer_science/gnu_linux/xcip.md
      - X: computer_science/gnu_linux/X.md
      - X-utilities: computer_science/gnu_linux/x-utilities.md
      - YAML: computer_science/gnu_linux/yaml.md
      - youtube-dl: computer_science/gnu_linux/youtube-dl.md
      - zip: computer_science/gnu_linux/zip.md
    - Android:
      - Apps: computer_science/android/apps.md
    - Programming:
      - Python:
        - Basics: computer_science/programming/python/basics.md
        - Debugging: computer_science/programming/python/debugging.md
        - Pandas: computer_science/programming/python/pandas.md
        - pip: computer_science/gnu_linux/programming/python/pip.md
        - Style: computer_science/programming/python/style.md
  - Cooking:
    - Recipes:
      - Eggplant kebap: cooking/recipes/eggplant_kebap.md
    #  - Music:
    #  - Electrical Engineering:
    #  - Machine Learning:
    #  - Math:
    #  - Pollution:
    #  - Languages:
    #    - Turkish:
    #  - Economy:
    #  - Botany:
  - Forking this wiki: forking_this_wiki.md
  - Contact: contact.md

plugins:
  - search
  - autolinks
  - git-revision-date-localized:
      type: timeago
  - minify:
      minify_html: true
  - section-index
  - mkdocs-newsletter

markdown_extensions:
  - abbr
  - admonition
  - meta
  - def_list
  - toc:
      permalink: ⚑
      baselevel: 2
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: '!!python/name:pymdownx.emoji.to_svg'
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
theme:
  name: material
  custom_dir: theme
  logo: img/logo.bmp
  features:
    - navigation.instant
    - navigation.top
  palette:
    # Light mode
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: blue grey
      accent: light blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: blue grey
      accent: light blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

extra_css:
  - stylesheets/extra.css
  - stylesheets/links.css

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/m0wer
    - icon: fontawesome/solid/rss
      link: https://m0wer.github.io/memento/newsletter/0_newsletter_index

repo_name: m0wer/memento
repo_url: https://github.com/m0wer/memento
