---
site_name: Memento
site_description: My personal digital garden
site_author: m0wer
site_url: https://m0wer.github.io/memento
nav:
  - Introduction: index.md
    #  - Projects:
    #  - Organization:
  - Computer Science:
    - GNU/Linux:
      - Tools:
        - android: computer_science/gnu_linux/android.md
        - android-studio: computer_science/gnu_linux/android-studio.md
        - anki: computer_science/gnu_linux/anki.md
        - ansible: computer_science/gnu_linux/ansible.md
        - apt: computer_science/gnu_linux/apt.md
        - bash: computer_science/gnu_linux/bash.md
        - blkid: computer_science/gnu_linux/blkid.md
        - c: computer_science/gnu_linux/c.md
        - coding: computer_science/gnu_linux/coding.md
        - cpupower: computer_science/gnu_linux/cpupower.md
        - debian: computer_science/gnu_linux/debian.md
        - dig: computer_science/gnu_linux/dig.md
        - docker: computer_science/gnu_linux/docker.md
        - eclipse: computer_science/gnu_linux/eclipse.md
        - elogind: computer_science/gnu_linux/elogind.md
        - emerge: computer_science/gnu_linux/emerge.md
        - equery: computer_science/gnu_linux/equery.md
        - esp8266: computer_science/gnu_linux/esp8266.md
        - exiftool: computer_science/gnu_linux/exiftool.md
        - fdisk: computer_science/gnu_linux/fdisk.md
        - ffmpeg: computer_science/gnu_linux/ffmpeg.md
        - find: computer_science/gnu_linux/find.md
        - firefox: computer_science/gnu_linux/firefox.md
        - ftp: computer_science/gnu_linux/ftp.md
        - genkernel: computer_science/gnu_linux/genkernel.md
        - genlop: computer_science/gnu_linux/genlop.md
        - gentoo: computer_science/gnu_linux/gentoo.md
        - git: computer_science/gnu_linux/git.md
        - gpg: computer_science/gnu_linux/gpg.md
        - gs: computer_science/gnu_linux/gs.md
        - i3wm: computer_science/gnu_linux/i3wm.md
        - ibus: computer_science/gnu_linux/ibus.md
        - imagemagick: computer_science/gnu_linux/imagemagick.md
        - iostat: computer_science/gnu_linux/iostat.md
        - iptables: computer_science/gnu_linux/iptables.md
        - isync: computer_science/gnu_linux/isync.md
        - jabber: computer_science/gnu_linux/jabber.md
        - java: computer_science/gnu_linux/java.md
        - jpegoptim: computer_science/gnu_linux/jpegoptim.md
        - kali: computer_science/gnu_linux/kali.md
        - kernel: computer_science/gnu_linux/kernel.md
        - khal: computer_science/gnu_linux/khal.md
        - khard: computer_science/gnu_linux/khard.md
        - kodi: computer_science/gnu_linux/kodi.md
        - latex: computer_science/gnu_linux/latex.md
        - layman: computer_science/gnu_linux/layman.md
        - libreoffice: computer_science/gnu_linux/libreoffice.md
        - lightdm: computer_science/gnu_linux/lightdm.md
        - linux: computer_science/gnu_linux/linux.md
        - luks: computer_science/gnu_linux/luks.md
        - lvm: computer_science/gnu_linux/lvm.md
        - markdown: computer_science/gnu_linux/markdown.md
        - mathjax: computer_science/gnu_linux/mathjax.md
        - mdadm: computer_science/gnu_linux/mdadm.md
        - mimeopen: computer_science/gnu_linux/mimeopen.md
        - molecule: computer_science/gnu_linux/molecule.md
        - msmtp: computer_science/gnu_linux/msmtp.md
        - music: computer_science/gnu_linux/music.md
        - neomutt: computer_science/gnu_linux/neomutt.md
        - netcat: computer_science/gnu_linux/netcat.md
        - nextcloud: computer_science/gnu_linux/nextcloud.md
        - nfs: computer_science/gnu_linux/nfs.md
        - nginx: computer_science/gnu_linux/nginx.md
        - nice: computer_science/gnu_linux/nice.md
        - nikola: computer_science/gnu_linux/nikola.md
        - octave: computer_science/gnu_linux/octave.md
        - openldap: computer_science/gnu_linux/openldap.md
        - openrc: computer_science/gnu_linux/openrc.md
        - openssl: computer_science/gnu_linux/openssl.md
        - pandas: computer_science/gnu_linux/pandas.md
        - pandoc: computer_science/gnu_linux/pandoc.md
        - pass: computer_science/gnu_linux/pass.md
        - pdfimages: computer_science/gnu_linux/pdfimages.md
        - pdftk: computer_science/gnu_linux/pdftk.md
        - pdfunite: computer_science/gnu_linux/pdfunite.md
        - pip: computer_science/gnu_linux/pip.md
        - portage: computer_science/gnu_linux/portage.md
        - postgresql: computer_science/gnu_linux/postgresql.md
        - pulseaudio: computer_science/gnu_linux/pulseaudio.md
        - python: computer_science/gnu_linux/python.md
        - qutebrowser: computer_science/gnu_linux/qutebrowser.md
        - radare2: computer_science/gnu_linux/radare2.md
        - ranger: computer_science/gnu_linux/ranger.md
        - rpi: computer_science/gnu_linux/rpi.md
        - rsnapshot: computer_science/gnu_linux/rsnapshot.md
        - rsync: computer_science/gnu_linux/rsync.md
        - rxvt-unicode: computer_science/gnu_linux/rxvt-unicode.md
        - sed: computer_science/gnu_linux/sed.md
        - shell: computer_science/gnu_linux/shell.md
        - shell-utils: computer_science/gnu_linux/shell-utils.md
        - shnsplit: computer_science/gnu_linux/shnsplit.md
        - smartmontools: computer_science/gnu_linux/smartmontools.md
        - ssh: computer_science/gnu_linux/ssh.md
        - ss: computer_science/gnu_linux/ss.md
        - stat: computer_science/gnu_linux/stat.md
        - sysctl: computer_science/gnu_linux/sysctl.md
        - systemd: computer_science/gnu_linux/systemd.md
        - taskwarrior: computer_science/gnu_linux/taskwarrior.md
        - tcpdump: computer_science/gnu_linux/tcpdump.md
        - telegraf: computer_science/gnu_linux/telegraf.md
        - telegram-cli: computer_science/gnu_linux/telegram-cli.md
        - terminal: computer_science/gnu_linux/terminal.md
        - termite: computer_science/gnu_linux/termite.md
        - tmux: computer_science/gnu_linux/tmux.md
        - tor: computer_science/gnu_linux/tor.md
        - vagrant: computer_science/gnu_linux/vagrant.md
        - vimdiff: computer_science/gnu_linux/vimdiff.md
        - vim: computer_science/gnu_linux/vim.md
        - virtualenvwrapper: computer_science/gnu_linux/virtualenvwrapper.md
        - weechat: computer_science/gnu_linux/weechat.md
        - wget: computer_science/gnu_linux/wget.md
        - xcip: computer_science/gnu_linux/xcip.md
        - X: computer_science/gnu_linux/X.md
        - x-utilities: computer_science/gnu_linux/x-utilities.md
        - yaml: computer_science/gnu_linux/yaml.md
        - youtube-dl: computer_science/gnu_linux/youtube-dl.md
        - zip: computer_science/gnu_linux/zip.md
    #    - Android:
    #  - Cooking:
    #  - Music:
    #  - Electrical Engineering:
    #  - Machine Learning:
    #  - Math:
    #  - Pollution:
    #  - Languages:
    #    - Turkish:
    #  - Economy:
    #  - Botany:
  - Forking this wiki: forking_this_wiki.md
  - Contact: contact.md

plugins:
  - search
  - autolinks
  - git-revision-date-localized:
      type: timeago
  - minify:
      minify_html: true
  - section-index
  - mkdocs-newsletter

markdown_extensions:
  - abbr
  - admonition
  - meta
  - def_list
  - toc:
      permalink: ⚑
      baselevel: 2
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: '!!python/name:pymdownx.emoji.to_svg'
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
theme:
  name: material
  custom_dir: theme
  logo: img/logo.bmp
  features:
    - navigation.instant
    - navigation.top
  palette:
    # Light mode
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: blue grey
      accent: light blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: blue grey
      accent: light blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

extra_css:
  - stylesheets/extra.css
  - stylesheets/links.css

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/m0wer
    - icon: fontawesome/solid/rss
      link: https://m0wer.github.io/memento/newsletter/0_newsletter_index

repo_name: m0wer/memento
repo_url: https://github.com/m0wer/memento
