---
site_name: The Blue Book
site_description: My personal digital garden
site_author: m0wer
site_url: https://m0wer.github.io/blue-book
nav:
  - Introduction: index.md
    #  - Projects:
    #  - Organization:
  - Computer Science:
    - GNU/Linux:
      - Tools:
        - android: computer_science/gnu_linux/tools/android.md
        - android-studio: computer_science/gnu_linux/tools/android-studio.md
        - anki: computer_science/gnu_linux/tools/anki.md
        - ansible: computer_science/gnu_linux/tools/ansible.md
        - apt: computer_science/gnu_linux/tools/apt.md
        - bash: computer_science/gnu_linux/tools/bash.md
        - blkid: computer_science/gnu_linux/tools/blkid.md
        - c: computer_science/gnu_linux/tools/c.md
        - coding: computer_science/gnu_linux/tools/coding.md
        - cpupower: computer_science/gnu_linux/tools/cpupower.md
        - debian: computer_science/gnu_linux/tools/debian.md
        - dig: computer_science/gnu_linux/tools/dig.md
        - docker: computer_science/gnu_linux/tools/docker.md
        - eclipse: computer_science/gnu_linux/tools/eclipse.md
        - elogind: computer_science/gnu_linux/tools/elogind.md
        - emerge: computer_science/gnu_linux/tools/emerge.md
        - equery: computer_science/gnu_linux/tools/equery.md
        - esp8266: computer_science/gnu_linux/tools/esp8266.md
        - exiftool: computer_science/gnu_linux/tools/exiftool.md
        - fdisk: computer_science/gnu_linux/tools/fdisk.md
        - ffmpeg: computer_science/gnu_linux/tools/ffmpeg.md
        - find: computer_science/gnu_linux/tools/find.md
        - firefox: computer_science/gnu_linux/tools/firefox.md
        - ftp: computer_science/gnu_linux/tools/ftp.md
        - genkernel: computer_science/gnu_linux/tools/genkernel.md
        - genlop: computer_science/gnu_linux/tools/genlop.md
        - gentoo: computer_science/gnu_linux/tools/gentoo.md
        - git: computer_science/gnu_linux/tools/git.md
        - gpg: computer_science/gnu_linux/tools/gpg.md
        - gs: computer_science/gnu_linux/tools/gs.md
        - i3wm: computer_science/gnu_linux/tools/i3wm.md
        - ibus: computer_science/gnu_linux/tools/ibus.md
        - imagemagick: computer_science/gnu_linux/tools/imagemagick.md
        - iostat: computer_science/gnu_linux/tools/iostat.md
        - iptables: computer_science/gnu_linux/tools/iptables.md
        - isync: computer_science/gnu_linux/tools/isync.md
        - jabber: computer_science/gnu_linux/tools/jabber.md
        - java: computer_science/gnu_linux/tools/java.md
        - jpegoptim: computer_science/gnu_linux/tools/jpegoptim.md
        - kali: computer_science/gnu_linux/tools/kali.md
        - kernel: computer_science/gnu_linux/tools/kernel.md
        - khal: computer_science/gnu_linux/tools/khal.md
        - khard: computer_science/gnu_linux/tools/khard.md
        - kodi: computer_science/gnu_linux/tools/kodi.md
        - latex: computer_science/gnu_linux/tools/latex.md
        - layman: computer_science/gnu_linux/tools/layman.md
        - libreoffice: computer_science/gnu_linux/tools/libreoffice.md
        - lightdm: computer_science/gnu_linux/tools/lightdm.md
        - linux: computer_science/gnu_linux/tools/linux.md
        - luks: computer_science/gnu_linux/tools/luks.md
        - lvm: computer_science/gnu_linux/tools/lvm.md
        - markdown: computer_science/gnu_linux/tools/markdown.md
        - mathjax: computer_science/gnu_linux/tools/mathjax.md
        - mdadm: computer_science/gnu_linux/tools/mdadm.md
        - mimeopen: computer_science/gnu_linux/tools/mimeopen.md
        - molecule: computer_science/gnu_linux/tools/molecule.md
        - msmtp: computer_science/gnu_linux/tools/msmtp.md
        - music: computer_science/gnu_linux/tools/music.md
        - neomutt: computer_science/gnu_linux/tools/neomutt.md
        - netcat: computer_science/gnu_linux/tools/netcat.md
        - nextcloud: computer_science/gnu_linux/tools/nextcloud.md
        - nfs: computer_science/gnu_linux/tools/nfs.md
        - nginx: computer_science/gnu_linux/tools/nginx.md
        - nice: computer_science/gnu_linux/tools/nice.md
        - nikola: computer_science/gnu_linux/tools/nikola.md
        - octave: computer_science/gnu_linux/tools/octave.md
        - openldap: computer_science/gnu_linux/tools/openldap.md
        - openrc: computer_science/gnu_linux/tools/openrc.md
        - openssl: computer_science/gnu_linux/tools/openssl.md
        - pandas: computer_science/gnu_linux/tools/pandas.md
        - pandoc: computer_science/gnu_linux/tools/pandoc.md
        - pass: computer_science/gnu_linux/tools/pass.md
        - pdfimages: computer_science/gnu_linux/tools/pdfimages.md
        - pdftk: computer_science/gnu_linux/tools/pdftk.md
        - pdfunite: computer_science/gnu_linux/tools/pdfunite.md
        - pip: computer_science/gnu_linux/tools/pip.md
        - portage: computer_science/gnu_linux/tools/portage.md
        - postgresql: computer_science/gnu_linux/tools/postgresql.md
        - pulseaudio: computer_science/gnu_linux/tools/pulseaudio.md
        - python: computer_science/gnu_linux/tools/python.md
        - qutebrowser: computer_science/gnu_linux/tools/qutebrowser.md
        - radare2: computer_science/gnu_linux/tools/radare2.md
        - ranger: computer_science/gnu_linux/tools/ranger.md
        - rpi: computer_science/gnu_linux/tools/rpi.md
        - rsnapshot: computer_science/gnu_linux/tools/rsnapshot.md
        - rsync: computer_science/gnu_linux/tools/rsync.md
        - rxvt-unicode: computer_science/gnu_linux/tools/rxvt-unicode.md
        - sed: computer_science/gnu_linux/tools/sed.md
        - shell: computer_science/gnu_linux/tools/shell.md
        - shell-utils: computer_science/gnu_linux/tools/shell-utils.md
        - shnsplit: computer_science/gnu_linux/tools/shnsplit.md
        - smartmontools: computer_science/gnu_linux/tools/smartmontools.md
        - ssh: computer_science/gnu_linux/tools/ssh.md
        - ss: computer_science/gnu_linux/tools/ss.md
        - stat: computer_science/gnu_linux/tools/stat.md
        - sysctl: computer_science/gnu_linux/tools/sysctl.md
        - systemd: computer_science/gnu_linux/tools/systemd.md
        - taskwarrior: computer_science/gnu_linux/tools/taskwarrior.md
        - tcpdump: computer_science/gnu_linux/tools/tcpdump.md
        - telegraf: computer_science/gnu_linux/tools/telegraf.md
        - telegram-cli: computer_science/gnu_linux/tools/telegram-cli.md
        - terminal: computer_science/gnu_linux/tools/terminal.md
        - termite: computer_science/gnu_linux/tools/termite.md
        - tmux: computer_science/gnu_linux/tools/tmux.md
        - tor: computer_science/gnu_linux/tools/tor.md
        - vagrant: computer_science/gnu_linux/tools/vagrant.md
        - vimdiff: computer_science/gnu_linux/tools/vimdiff.md
        - vim: computer_science/gnu_linux/tools/vim.md
        - virtualenvwrapper: computer_science/gnu_linux/tools/virtualenvwrapper.md
        - weechat: computer_science/gnu_linux/tools/weechat.md
        - wget: computer_science/gnu_linux/tools/wget.md
        - xcip: computer_science/gnu_linux/tools/xcip.md
        - X: computer_science/gnu_linux/tools/X.md
        - x-utilities: computer_science/gnu_linux/tools/x-utilities.md
        - yaml: computer_science/gnu_linux/tools/yaml.md
        - youtube-dl: computer_science/gnu_linux/tools/youtube-dl.md
        - zip: computer_science/gnu_linux/tools/zip.md
    #    - Android:
    #  - Cooking:
    #  - Music:
    #  - Electrical Engineering:
    #  - Machine Learning:
    #  - Math:
    #  - Pollution:
    #  - Languages:
    #    - Turkish:
    #  - Economy:
    #  - Botany:
  - Contact: contact.md

plugins:
  - search
  - autolinks
  - git-revision-date-localized:
      type: timeago
  - minify:
      minify_html: true
  - section-index
  - mkdocs-newsletter

markdown_extensions:
  - abbr
  - admonition
  - meta
  - def_list
  - toc:
      permalink: ⚑
      baselevel: 2
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: '!!python/name:pymdownx.emoji.to_svg'
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
theme:
  name: material
  custom_dir: theme
  logo: img/logo.bmp
  features:
    - navigation.instant
    - navigation.top
  palette:
    # Light mode
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: blue grey
      accent: light blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: blue grey
      accent: light blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

extra_css:
  - stylesheets/extra.css
  - stylesheets/links.css

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/m0wer
    - icon: fontawesome/solid/rss
      link: https://m0wer.github.io/blue-book/newsletter/0_newsletter_index

repo_name: m0wer/blue-book
repo_url: https://github.com/m0wer/blue-book
